[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json", "secrets", "uuid"] }
rocket_db_pools = { version = "0.2.0", features = ["diesel_postgres"] }
shared = { version = "0.1.0", path = "../shared" }
